platform :ios, '8.0'

inhibit_all_warnings!

target ‘iOS-Learning-Demo’ do
    pod 'SDAutoLayout'
    pod 'ReactiveObjC'
    pod 'YYModel'
    pod 'YBImageBrowser'
    pod 'TZImagePickerController'
    
    pod 'BaiduMapKit', '~> 4.2.1'
    pod 'BMKLocationKit', '~> 1.4.0'
end
